language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --dev --pre
script:
- python -c 'import remotevbox'
- black .
before_deploy:
- rm -rf dist Pipfile.lock remotevbox.egg-info
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: aBgzJ72w4DWg9+ukCakiRSOj8rVO63pPdfkA9ymrstAaYCX79efUm9HDSmLulows3wnrkqgznJ/U3DO2emN/rWYfwSlCf9Yi4r0mnjTujsyHbojtrV74RHuIE/y9DkiWFGgs6xt5wrv3sVD9mjWLIqY9/iJof12UgrtR8cxveAdYi5N746vrlB3rDXezylAivRd96qDIRgec9Tx4Kqje+f0GPJx8Guru16CWWRRCQqJF6CZDNxpxTQZyIMhWZolNFBxWlGec0YgVadzIR37XG+kCOIo09F5obv4t9O+Ut2wUU1/17BWf/fB3PZdOyjtpSdhHfNF4BUYrMJn+3nUaRraib0raIQwqtZbLyPU6KsAHPEsAtPhNbsutidRIfyRm5nInbfg0Ef0AfTnd2Wj2yO3B0vomRVl3sWJ1DpBhmjVDj6QCFAfsurNE4A/OjIpqTrJiLs+L/Sk/A6LdVmJqVLpLsrJfuJWfvccFsEncE/7cXkB0m9uwrqQ0pzi+SnrtHpBiQc9K2XqNs5TIphPLgbJ/J14R3SYVd+tDaA5F5VA6wNeE/vz3yoWi/HI2GBu5sWK0pVmqynFC2/iHeATppYPGaPZC8/a9JOrHGCNzgNpEtyi3PFXIeUfRcBCmKIIe0DmxS2hcdZNpUTKbTDLqQK7awXniXT0U7slRRxd91+w=
  on:
    tags: true
    branch: master
